# utils/languages.py

LANGUAGES = {
    "English (Indian)": "en-IN",
    "English (US)": "en-US",
    "Hindi": "hi-IN",
    "Bengali": "bn-IN",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Marathi": "mr-IN",
    "Gujarati": "gu-IN",
    "Kannada": "kn-IN",
    "Malayalam": "ml-IN",
    "Punjabi": "pa-IN",
    "Urdu": "ur-IN",
    "Spanish": "es-ES",
    "French": "fr-FR",
    "German": "de-DE",
    "Chinese (Mandarin)": "zh-CN",
    "Arabic": "ar-SA",
    "Japanese": "ja-JP",
    "Korean": "ko-KR",
    "Russian": "ru-RU",
    "Portuguese (Brazil)": "pt-BR",
    "Italian": "it-IT",
    "Thai": "th-TH",
    "Vietnamese": "vi-VN",
    "Dutch": "nl-NL",
    "Greek": "el-GR",
    "Hebrew": "he-IL",
    "Indonesian": "id-ID",
    "Polish": "pl-PL",
    "Turkish": "tr-TR",
    "Swedish": "sv-SE",
    "Czech": "cs-CZ",
    "Ukrainian": "uk-UA",
    "Hungarian": "hu-HU",
    "Romanian": "ro-RO",
    "Finnish": "fi-FI",
    "Norwegian": "no-NO",
    "Danish": "da-DK"
}

